project:
  type: website

website:
  title: "Grace V. Ringlein"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      # - href: teaching.qmd
      #   text: Teaching
      # - href: education.qmd
      #   text: Education
      - href: GR_CV_03232026.pdf
        text: CV
      # - href: fun.qmd
      #   text: Fun

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

