---
title: "Selected Publications"
---

*For a full publication list, see my [CV](GR_CV_03232026.pdf) or [Google Scholar](https://scholar.google.com/citations?user=8EyqLFQAAAAJ&hl=en&oi=ao.).*

## Methods for Causal Inference

**Ringlein, G. V.**, Nguyen, T. Q., Zandi, P. P., Stuart, E. A., & Parikh, H. (2025). Demystifying proximal causal inference. *arXiv*. Under review. [doi:10.48550/arxiv.2512.24413](https://doi.org/10.48550/ARXIV.2512.24413)

Nguyen, T. Q., Nabi, R., Yang, F., **Ringlein, G. V.**, & Stuart, E. A. Self-separated and self-connected models for mediator and outcome missingness in mediation analysis. *Statistical Science*. In press. [doi:10.48550/arXiv.2411.07221](https://doi.org/10.48550/arXiv.2411.07221).

## Mental Health Care Utilization: Electronic Health Records Analyses

Ettman, C. K., Jeon, K., Dohlman, P., **Ringlein, G. V.**, Straub, J., et al. Psychiatric services following suicide-related hospital visits: An analysis of electronic health records among patients with depression. Under review.

Hong, H., Zhao, C., Jeon, K., Goicoechea, E. B., Brantner, C. L., **Ringlein, G. V.**, et al. Comparative effectiveness of antidepressants for depression using EHRs from two health systems. *BMC Psychiatry* (2026). [doi:/10.1186/s12888-026-08159-x](https://doi.org/10.1186/s12888-026-08159-x)

Ettman, C. K., **Ringlein, G. V.**, Dohlman, P., Straub, J., Brantner, C. L., Chin, E. T., et al. (2025). Trends in mental health care and telehealth use across area deprivation: An analysis of electronic health records from 2016–2024. *PNAS Nexus*, pgaf016. [doi:10.1093/pnasnexus/pgaf016](https://doi.org/10.1093/pnasnexus/pgaf016)

Ettman, C. K., Brantner, C. L., Goicoechea, E. B., Dohlman, P., **Ringlein, G. V.**, Straub, J., et al. (2025). Gaps in psychiatric care before and after the COVID-19 pandemic among patients with depression using electronic health records. *Psychiatry Research*, 344, 116354. [doi:10.1016/j.psychres.2025.116354](https://doi.org/10.1016/j.psychres.2025.116354)

Brantner, C. L., Yu, W., Zhao, C., Jeon, K., **Ringlein, G. V.**, Wang, Q., et al. (2025). The challenges of integrating diverse data sources: A case study in major depression. *Health Services and Outcomes Research Methodology*. [doi:10.1007/s10742-025-00363-8](https://doi.org/10.1007/s10742-025-00363-8)

## Financial Strain, Job loss, and Mental Health

Mady L. J. , **Ringlein G. V.,** Satpathy-Horton R., Stuart E. A., Galea S., Ettman C. K. (2026). Pre-existing financial circumstance, job loss, and probable depression among U.S. adults: a prospective population-based cohort study. *Lancet Regional Health Americas,* 63. [doi:/10.1016/j.lana.2026.101590](https://doi.org/10.1016/j.lana.2026.101590)

**Ringlein, G. V.**, Ettman, C. K., & Stuart, E. A. (2024). Income or job loss and psychological distress during the COVID-19 pandemic. *JAMA Network Open*, 7(7), e2424601. [doi:10.1001/jamanetworkopen.2024.24601](https://doi.org/10.1001/jamanetworkopen.2024.24601)

Ettman, C. K., Fan, A. Y., Philips, A. P., Adam, G. P., **Ringlein, G.**, Clark, M. A., et al. (2023). Financial strain and depression in the U.S.: A scoping review. *Translational Psychiatry*, 13(1), 168. [doi:10.1038/s41398-023-02460-z](https://doi.org/10.1038/s41398-023-02460-z)

## Pediatric Mental Health and Neuroimaging

<!-- *Selected Publications affiliated with my postbaccalaureate fellowship at National Institute of Mental Health.* -->

Zugman, A., **Ringlein, G. V.**, Finn, E. S., Lewis, K. M., Berman, E., Silverman, W. K., et al. (2025). Brain functional connectivity and anatomical features as predictors of cognitive behavioral therapy outcome for anxiety in youths. *Psychological Medicine*, 55, e91. [doi:10.1017/S0033291724003131](https://doi.org/10.1017/S0033291724003131)

Lossio-Ventura, J. A., Frank, S., **Ringlein, G.**, Bonson, K., Olszko, A., Knobel, A., et al. (2025). Automated classification of exposure and encourage events in speech data from pediatric OCD treatment. *JAMIA Open*, 8(6), ooaf127. [doi:10.1093/jamiaopen/ooaf127](https://doi.org/10.1093/jamiaopen/ooaf127)

Kirk, P. A., Qamar, P., Zugman, A., Abend, R., Frank, S., **Ringlein, G. V.**, et al. (2025). The relations among anxiety, movie-watching, and in-scanner motion. *Human Brain Mapping*, 46(4), e70163. [doi:10.1002/hbm.70163](https://doi.org/10.1002/hbm.70163)


<!-- ## Climate Modelling  -->

<!-- Gnanadesikan, A., Speller, C. M., **Ringlein, G.**, San Soucie, J., Thomas, J., & Pradal, M.-A. (2020). Feedbacks driving interdecadal variability in southern ocean convection in climate models: A coupled oscillator mechanism. *Journal of Physical Oceanography*, 50(8), 2227–2249. [doi:10.1175/JPO-D-20-0037.1](https://doi.org/10.1175/JPO-D-20-0037.1) -->